{
 "title": "Exchange | DAG - Replication - Service Health",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "DB's Mounted Historical View",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "$tag_Host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "Host::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DAG",
     "select": [
      [
       { "params": [ "Active" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "Host::tag",
       "operator": "=",
       "value": "\"ExchangeServer\""
      }
     ]
    },
    {
     "alias": "$tag_Host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "Host::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DAG",
     "select": [
      [
       { "params": [ "Active" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "Host::tag",
       "operator": "=",
       "value": "\"ExchangeServer\""
      }
     ]
    },
    {
     "alias": "$tag_Host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "Host::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DAG",
     "select": [
      [
       { "params": [ "Active" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "Host::tag",
       "operator": "=",
       "value": "\"ExchangeServer\""
      }
     ]
    },
    {
     "alias": "$tag_Host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "Host::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DAG",
     "select": [
      [
       { "params": [ "Active" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "Host::tag",
       "operator": "=",
       "value": "\"ExchangeServer\""
      }
     ]
    },
    {
     "alias": "$tag_Host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "Host::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DAG",
     "select": [
      [
       { "params": [ "Active" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "Host::tag",
       "operator": "=",
       "value": "\"ExchangeServer\""
      }
     ]
    },
    {
     "alias": "$tag_Host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "Host::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DAG",
     "select": [
      [
       { "params": [ "Active" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "Host::tag",
       "operator": "=",
       "value": "\"ExchangeServer\""
      }
     ]
    }
   ]
  },
  {
   "title": "ServerName",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "DAG",
     "select": [
      [
       { "params": [ "Server" ], "type": "field" }
      ]
     ],
     "tags": [
      {
       "key": "Host::tag",
       "operator": "=",
       "value": "\"ExchangeServer\""
      }
     ]
    }
   ]
  },
  {
   "title": "Mounted",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "DAG",
     "select": [
      [
       { "params": [ "Active" ], "type": "field" }
      ]
     ],
     "tags": [
      {
       "key": "Host::tag",
       "operator": "=",
       "value": "\"ExchangeServer\""
      }
     ]
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "backPressure",
     "select": [
      [
       { "params": [ "PressureValue" ], "type": "field" }
      ]
     ],
     "tags": [
      {
       "key": "Host::tag",
       "operator": "=",
       "value": "\"ExchangeServer\""
      }
     ]
    }
   ]
  },
  {
   "title": "ServerName",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "measurement": "DAG",
     "select": [
      [
       { "params": [ "Server" ], "type": "field" }
      ]
     ],
     "tags": [
      {
       "key": "Host::tag",
       "operator": "=",
       "value": "\"ExchangeServer\""
      }
     ]
    }
   ]
  },
  {
   "title": "Mounted",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "DAG",
     "select": [
      [
       { "params": [ "Active" ], "type": "field" }
      ]
     ],
     "tags": [
      {
       "key": "Host::tag",
       "operator": "=",
       "value": "\"ExchangeServer\""
      }
     ]
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "backPressure",
     "select": [
      [
       { "params": [ "PressureValue" ], "type": "field" }
      ]
     ],
     "tags": [
      {
       "key": "Host::tag",
       "operator": "=",
       "value": "\"ExchangeServer\""
      }
     ]
    }
   ]
  },
  {
   "title": "ServerName",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "DAG",
     "select": [
      [
       { "params": [ "Server" ], "type": "field" }
      ]
     ],
     "tags": [
      {
       "key": "Host::tag",
       "operator": "=",
       "value": "\"ExchangeServer\""
      }
     ]
    }
   ]
  },
  {
   "title": "Mounted",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "DAG",
     "select": [
      [
       { "params": [ "Active" ], "type": "field" }
      ]
     ],
     "tags": [
      {
       "key": "Host::tag",
       "operator": "=",
       "value": "\"ExchangeServer\""
      }
     ]
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "backPressure",
     "select": [
      [
       { "params": [ "PressureValue" ], "type": "field" }
      ]
     ],
     "tags": [
      {
       "key": "Host::tag",
       "operator": "=",
       "value": "\"ExchangeServer\""
      }
     ]
    }
   ]
  },
  {
   "title": "Services Running",
   "type": "table",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 9 },
   "targets": [
    {
     "measurement": "Service",
     "select": [
      [
       { "params": [ "Status" ], "type": "field" }
      ],
      [
       { "params": [ "Role" ], "type": "field" }
      ],
      [
       { "params": [ "Server" ], "type": "field" }
      ]
     ],
     "tags": [
      {
       "key": "Host::tag",
       "operator": "=",
       "value": "\"ExchangeServer\""
      }
     ]
    }
   ]
  },
  {
   "title": "Services Running",
   "type": "table",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 9 },
   "targets": [
    {
     "measurement": "Service",
     "select": [
      [
       { "params": [ "Status" ], "type": "field" }
      ],
      [
       { "params": [ "Role" ], "type": "field" }
      ],
      [
       { "params": [ "Server" ], "type": "field" }
      ]
     ],
     "tags": [
      {
       "key": "Host::tag",
       "operator": "=",
       "value": "\"ExchangeServer\""
      }
     ]
    }
   ]
  },
  {
   "title": "Services Running",
   "type": "table",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 9 },
   "targets": [
    {
     "measurement": "Service",
     "select": [
      [
       { "params": [ "Status" ], "type": "field" }
      ],
      [
       { "params": [ "Role" ], "type": "field" }
      ],
      [
       { "params": [ "Server" ], "type": "field" }
      ]
     ],
     "tags": [
      {
       "key": "Host::tag",
       "operator": "=",
       "value": "\"ExchangeServer\""
      }
     ]
    }
   ]
  },
  {
   "title": "ServerName",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "measurement": "DAG",
     "select": [
      [
       { "params": [ "Server" ], "type": "field" }
      ]
     ],
     "tags": [
      {
       "key": "Host::tag",
       "operator": "=",
       "value": "\"ExchangeServer\""
      }
     ]
    }
   ]
  },
  {
   "title": "Mounted",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "DAG",
     "select": [
      [
       { "params": [ "Active" ], "type": "field" }
      ]
     ],
     "tags": [
      {
       "key": "Host::tag",
       "operator": "=",
       "value": "\"ExchangeServer\""
      }
     ]
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "backPressure",
     "select": [
      [
       { "params": [ "PressureValue" ], "type": "field" }
      ]
     ],
     "tags": [
      {
       "key": "Host::tag",
       "operator": "=",
       "value": "\"ExchangeServer\""
      }
     ]
    }
   ]
  },
  {
   "title": "ServerName",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "DAG",
     "select": [
      [
       { "params": [ "Server" ], "type": "field" }
      ]
     ],
     "tags": [
      {
       "key": "Host::tag",
       "operator": "=",
       "value": "\"ExchangeServer\""
      }
     ]
    }
   ]
  },
  {
   "title": "Mounted",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "DAG",
     "select": [
      [
       { "params": [ "Active" ], "type": "field" }
      ]
     ],
     "tags": [
      {
       "key": "Host::tag",
       "operator": "=",
       "value": "\"ExchangeServer\""
      }
     ]
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "backPressure",
     "select": [
      [
       { "params": [ "PressureValue" ], "type": "field" }
      ]
     ],
     "tags": [
      {
       "key": "Host::tag",
       "operator": "=",
       "value": "\"ExchangeServer\""
      }
     ]
    }
   ]
  },
  {
   "title": "ServerName",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "measurement": "DAG",
     "select": [
      [
       { "params": [ "Server" ], "type": "field" }
      ]
     ],
     "tags": [
      {
       "key": "Host::tag",
       "operator": "=",
       "value": "\"ExchangeServer\""
      }
     ]
    }
   ]
  },
  {
   "title": "Mounted",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "DAG",
     "select": [
      [
       { "params": [ "Active" ], "type": "field" }
      ]
     ],
     "tags": [
      {
       "key": "Host::tag",
       "operator": "=",
       "value": "\"ExchangeServer\""
      }
     ]
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "backPressure",
     "select": [
      [
       { "params": [ "PressureValue" ], "type": "field" }
      ]
     ],
     "tags": [
      {
       "key": "Host::tag",
       "operator": "=",
       "value": "\"ExchangeServer\""
      }
     ]
    }
   ]
  },
  {
   "title": "Services Running",
   "type": "table",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 18 },
   "targets": [
    {
     "measurement": "Service",
     "select": [
      [
       { "params": [ "Status" ], "type": "field" }
      ],
      [
       { "params": [ "Role" ], "type": "field" }
      ],
      [
       { "params": [ "Server" ], "type": "field" }
      ]
     ],
     "tags": [
      {
       "key": "Host::tag",
       "operator": "=",
       "value": "\"ExchangeServer\""
      }
     ]
    }
   ]
  },
  {
   "title": "Services Running",
   "type": "table",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 18 },
   "targets": [
    {
     "measurement": "Service",
     "select": [
      [
       { "params": [ "Status" ], "type": "field" }
      ],
      [
       { "params": [ "Role" ], "type": "field" }
      ],
      [
       { "params": [ "Server" ], "type": "field" }
      ]
     ],
     "tags": [
      {
       "key": "Host::tag",
       "operator": "=",
       "value": "\"ExchangeServer\""
      }
     ]
    }
   ]
  },
  {
   "title": "Services Running",
   "type": "table",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 18 },
   "targets": [
    {
     "measurement": "Service",
     "select": [
      [
       { "params": [ "Status" ], "type": "field" }
      ],
      [
       { "params": [ "Role" ], "type": "field" }
      ],
      [
       { "params": [ "Server" ], "type": "field" }
      ]
     ],
     "tags": [
      {
       "key": "Host::tag",
       "operator": "=",
       "value": "\"ExchangeServer\""
      }
     ]
    }
   ]
  },
  {
   "title": "Exchange DAG Replication Health",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "measurement": "Replication",
     "select": [
      [
       { "params": [ "DagName" ], "type": "field" }
      ],
      [
       { "params": [ "Check" ], "type": "field" }
      ],
      [
       { "params": [ "Result" ], "type": "field" }
      ],
      [
       { "params": [ "Error" ], "type": "field" }
      ]
     ],
     "tags": [
      {
       "key": "Host::tag",
       "operator": "=",
       "value": "\"ZAMEX16-DAG1\""
      }
     ]
    }
   ]
  }
 ]
}